### ISSUE TITLE
2d-calibration-make-calc: TypeError: %d format: a number is required, not numpy.float64

### ISSUE THREAD

**Issue by dianachinezon** [RigacciOrg/py-qmc5883l#6] opened 2020-06-03 12:29 UTC
I followed the steps described in Calibration section.
Unfortunately, when I run the 2d-calibration-make-calc script I get the following error: 

Traceback (most recent call last):
  File "2d-calibration-make-calc", line 269, in <module>
    x2-cx, y2-cy)  # Example point (dot)
TypeError: %d format: a number is required, not numpy.float64

I am not sure how to fix this after some searches on the internet. Could you please advise regarding this error?
Many thanks for writing this library!

**Comment by RigacciOrg** [comment] 2020-06-04 14:11
Please, can you upload here the file created by the **2d-calibration-get-samples** script? It was generated by the **2d-calibration-get-samples** script and it should be named something like **magnet-data_YYYYmmdd_HHMM.txt**.

**Comment by david-lemasurier** [comment] 2020-06-07 00:58
[magnet-data_20200606_2035.txt](https://github.com/RigacciOrg/py-qmc5883l/files/4741252/magnet-data_20200606_2035.txt)
I am having a similar issue:
./2d-calibration-make-calc:121: RuntimeWarning: invalid value encountered in sqrt
  res1=np.sqrt(up/down1)
Traceback (most recent call last):
  File "./2d-calibration-make-calc", line 268, in <module>
    x2-cx, y2-cy)  # Example point (dot)
TypeError: %d format: a number is required, not numpy.float64

**Comment by RigacciOrg** [comment] 2020-06-09 06:18
Thank you for your feedback! The problem now is with me understanding the math :-)
The error comes from a sqrt function applied to a negative value, which returns a Not-A-Number object. Formulas applied by the ellipse_semi_axes_length() function are rather hard to me (I got them from some programming examples), so I will have some hard work in debugging.
Please stay tuned.

**Comment by RigacciOrg** [comment] 2020-06-09 06:47
I visually inspected the data into the **magnet-data_20200606_2035.txt** file. The expected shape should be an ellipse roughly centered into the origin (the 0, 0 point). As you can see it is rather chaotic instead. I don't know if applied formulas should extract a valid fitting ellipse neverthless (i.e. the error is still an error and should be catched and handled properly), but anyway I think that the extrapolated data will be very scary starting from that data.
![scattered-points](https://user-images.githubusercontent.com/863803/84114640-ff7ebb80-aa2c-11ea-96af-a4f514616540.png)

**Comment by RigacciOrg** [comment] 2020-06-11 07:37
I just committed cb6e9c8baa283102d9977ab24145db7affa3c0f1 a new **2d-calibration-make-calc** version, which includes a **workaround** for those cases giving invalid axes (i.e. a **square root of a negative number**, giving a nan not-a-number result). I'm definitely not a mathematician, so I cannot understand the formulas I used. Please see the web references included into the script itself.
As far I understand, the case of negative number under square root is rather weird, caused by strange input datasets. The script uses the alternative method only if the original one fails, in this case **a warning is placed into the resulting gnuplot script**, as a comment.
Please, always **check visually the gnuplot graph**, to see if fitting ellipse is good enough in respect of data points.
The graph obtained from the problematic dataset is attached below, you can see how weird are the points!
![magnet-data_20200606_2035](https://user-images.githubusercontent.com/863803/84358139-ff1a2800-abc6-11ea-9a77-f157927e982b.png)

**Closed as completed by RigacciOrg** 2020-06-11 07:37 UTC
